### ISSUE TITLE
app version checker does not work when implemented with the following libraries.

### ISSUE THREAD

**Issue by GiovanniPoggi** [X-SLAYER/app_version_checker#16]
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0-beta.21
  flutter_downloader: ^1.9.1
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  stroke_text: ^0.0.2
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1
  flutter_app_version_checker: ^0.3.2
```

if you add the listed libraries, the app doesn't work anymore, if you remove flutter_app_version_checker the app works again. Even if I don't use the flutter_app_version_checker library at all, it still doesn't work. If you run a test, the app doesn't start and stays on a black screen.
If you remove the library everything starts working normally again. How can I fix? Thank you
